# Change these first
owner: EaseAccess24 # Your GitHub organization or username, where this repository lives
repo: ea24-health-check # The name of this repository

sites:
  - name: EaseAccess24 Staging
    url: https://staging.easeaccess24.com/
  - name: EaseAccess24
    url: https://www.easeaccess24.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: custom-domain.com
  baseUrl: /ea24-health-check
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/logo.svg
  name: EaseAccess24 Uptime Monitor
  introTitle: "EaseAccess24 Uptime Monitor"
  introMessage: Real-time uptime monitoring for EaseAccess24 services
  favicon: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/favicon.svg
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/EaseAccess24/ea24-health-check

# Check interval (in minutes)
interval: 5

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
